# Generated by Django 5.2.1 on 2025-06-08 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('valid_days', models.JSONField()),
                ('base_distance_km', models.FloatField()),
                ('base_price', models.FloatField()),
                ('additional_price_per_km', models.FloatField()),
                ('waiting_charge_per_minute', models.FloatField()),
                ('free_wait_time_minutes', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pricing_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricingconfig')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('multiplier', models.FloatField()),
                ('pricing_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='pricing.pricingconfig')),
            ],
        ),
    ]
