# Generated by Django 5.2.1 on 2025-06-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricinglog',
            old_name='user',
            new_name='actor',
        ),
        migrations.AddField(
            model_name='pricinglog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
